###########################################################################
#
#	Makefile to build sertest
#
###########################################################################

MK_OS		= host
MK_ELF_TARGET 	= sertest

MK_SRC_FILES = sertest.c

include ../../rules/mkRules.mk

