###########################################################################
#
#	Makefile to build sertest
#
###########################################################################

MK_OS			= host
MK_ELF_TARGET 	= sertest

MK_SRC_FILES = sertest.c

LDLIBS += -lpthread

include ../../rules/mkRules.mk

