###########################################################################
#
# tiny45-flasher Makefile
#
###########################################################################

MK_OS				= avr
MK_AVR_MCU			= m128
MK_AVR_FREQ			= 16MHz
MK_AVR_PROGRAMMER  ?= BootHost
					  
MK_HEX_TARGET	= qd-test
MK_SRC_FILES	= qd-test.c QD.c Hardware.c UART.c Timer.c

include ../../rules/mkRules.mk

