###########################################################################
#
#	Makefile to build backtrace
#
###########################################################################

MK_OS		= host
MK_ELF_TARGET 	= backtrace

MK_SRC_FILES = backtrace.c

MK_ADD_SYMBOLS = 1

include ../../../rules/mkRules.mk

