###########################################################################
#
#	Makefile to build pthread-test
#
###########################################################################

MK_OS			= host
MK_ELF_TARGET 	= pthread-test

MK_SRC_FILES 	= pthread-test.c

LDLIBS += -lpthread

include ../../rules/mkRules.mk

