###########################################################################
#
#	Makefile to build CountLineEndings
#
###########################################################################

MK_OS			= host
MK_ELF_TARGET 	= CountLineEndings

MK_SRC_FILES = CountLineEndings.c

include ../../../rules/mkRules.mk

