###########################################################################
#
#	Makefile to build CountLineEndings
#
###########################################################################

MK_OS			= cygwin
MK_BIN_TARGET 	= CountLineEndings

MK_SRC_FILES = CountLineEndings.c

include ../../../rules/mkRules.mk

