###########################################################################
#
#	Makefile to build args
#
###########################################################################

MK_OS			= host
MK_ELF_TARGET 	= args

MK_SRC_FILES 	= args.c

include ../../../rules/mkRules.mk

