###########################################################################
#
#	Makefile to build the baisc flasher for the olimex LPC2124 board
#
###########################################################################

MK_OS			    = lpc
MK_HEX_TARGET 	    = flasher

MK_SRC_FILES 	    = flasher.c
MK_LPC_PROGRAMMER	= lpc21isp

include ../../rules/mkRules.mk

