###########################################################################
#
# lcd-test Makefile
#
###########################################################################

MK_HEX_TARGET	= lcd-test
MK_SRC_FILES	= lcd-test.c lcd-api.c lcd-hal-avr.c Delay.c Timer.c

include ../3pi-rules.mk

