###########################################################################
#
#	Makefile to build nettest
#
###########################################################################

MK_OS		= host
MK_ELF_TARGET 	= udp-server

MK_SRC_FILES = udp-server.c

#LDLIBS += -lpthread

include ../../rules/mkRules.mk

