###########################################################################
#
#	Makefile to build the rts test program
#
###########################################################################

MK_OS			= host
MK_ELF_TARGET 	= rts

MK_SRC_FILES = rts.c

include ../../rules/mkRules.mk

