###########################################################################
#
#	Makefile to build sertest
#
###########################################################################

MK_OS			= host
MK_ELF_TARGET 	= srec2bin

MK_SRC_FILES = srec2bin.cpp srec.cpp

include ../../rules/mkRules.mk

