###########################################################################
#
# lcd-robostix Makefile
#
###########################################################################

MK_OS				= avr
MK_AVR_MCU			= m168
MK_AVR_FREQ			= 8MHz
MK_AVR_PROGRAMMER  ?= BootHost

MK_HEX_TARGET	= one-wire-test
MK_SRC_FILES	= one-wire-test.c one-wire.c UART.c Delay.c Timer.c

include ../../rules/mkRules.mk

