###########################################################################
#
#	robovero flash-led
#
#	A simple LED flasher
#
###########################################################################

TARGET	= flash-led

SRCS 	= cr_startup_lpc17.c \
	  main.c \
	  tasks.c \
	  queue.c \
	  list.c \
	  port.c \
	  heap_1.c

include ../../lpc17xx/lpc17xx.mk

