###########################################################################
#
# lcd-robostix Makefile
#
###########################################################################

MK_OS				= avr
MK_AVR_MCU			= m88
MK_AVR_FREQ			= 8MHz
MK_AVR_PROGRAMMER  ?= stk500

MK_HEX_TARGET	= lcd-m168
MK_SRC_FILES	= lcd-m168.c lcd-api.c lcd-hal-avr.c Delay.c Timer.c

include ../../rules/mkRules.mk

