#!/bin/sh
#
# Start the gpio-event driver
#

start() {
        echo "Starting gpio-event..."

        # load driver
        /sbin/modprobe gpio-event
}
stop() {
        echo "Stopping gpio-event..."

	/sbin/modprobe -r gpio-event
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

