###########################################################################
#
#	Makefile to build args
#
###########################################################################

MK_OS			= host
#MK_HOST_OS 		= mingw
MK_ELF_TARGET 	= args-env

MK_SRC_FILES 	= args-env.c

include ../../../rules/mkRules.mk

