###########################################################################
#
#	Makefile to build CountLineEndings
#
###########################################################################

MK_OS			= host
MK_ELF_TARGET 	= packet-parser

MK_SRC_FILES = packet-parser.c bioloid-pkt.c Log.c

all: svn-version.h

include ../../rules/mkRules.mk


