###########################################################################
#
# tiny45-flasher Makefile
#
###########################################################################

MK_OS				= avr
MK_AVR_MCU			= t45
MK_AVR_FREQ			= 1MHz
MK_AVR_PROGRAMMER  ?= stk500
					  
MK_HEX_TARGET	= tiny45-flasher
MK_SRC_FILES	= tiny45-flasher.c

include ../../rules/mkRules.mk

