###########################################################################
#
#	Makefile to build utils
#
###########################################################################

MK_OS = none

MK_SRC_FILES = 2dos/ args/ CountLineEndings/ crc32/ hd/

include ../../rules/mkRules.mk

