###########################################################################
#
# Simple-Flasher Makefile
#
###########################################################################

MK_OS				= avr
MK_AVR_MCU			= m168
MK_AVR_FREQ			= 8MHz
MK_AVR_PROGRAMMER  ?= stk500
					  
MK_HEX_TARGET	= baby-o-tach
MK_SRC_FILES	= baby-o-tach.c UART.c Hardware.c

include ../../rules/mkRules.mk

