###########################################################################
#
#	Makefile to build crc32
#
###########################################################################

ifeq ($(MK_OS),)		  
MK_OS			= host
endif

MK_BIN_TARGET 	= hello-world

MK_SRC_FILES 	= hello-world.c

include ../rules/mkRules.mk

