###########################################################################
#
# tiny45-flasher Makefile
#
###########################################################################

MK_OS				= avr
MK_AVR_MCU			= t25
MK_AVR_FREQ			= 1MHz
MK_AVR_PROGRAMMER	= STK500
					  
MK_HEX_TARGET	= tiny45-tach
MK_SRC_FILES	= tiny45-tach.c

include ../../rules/mkRules.mk

