###########################################################################
#
# flasher-m168 Makefile
#
###########################################################################

MK_OS				= avr
MK_AVR_MCU			= m32u4
MK_AVR_FREQ			= 16MHz
MK_AVR_PROGRAMMER  ?= teensy

MK_HEX_TARGET	= heartbeat
MK_SRC_FILES	= heartbeat.c

include ../../rules/mkRules.mk

