###########################################################################
#
#	Makefile to build the utilities
#
###########################################################################

MK_OS = none

MK_SRC_FILES = src/ scripts/

include ../rules/mkRules.mk

