###########################################################################
#
#	Makefile to build nettest
#
###########################################################################

MK_OS		= host
MK_ELF_TARGET 	= udp-client

MK_SRC_FILES = udp-client.c

#LDLIBS += -lpthread

include ../../rules/mkRules.mk

