###########################################################################
#
# bioloid Makefile
#
###########################################################################

MK_OS			= avr
MK_AVR_MCU		= m128
MK_AVR_FREQ		= 16MHz
					  
MK_HEX_TARGET	= bioloid
MK_SRC_FILES	= bioloid.c

include ../../rules/mkRules.mk

