###########################################################################
#
#	Makefile to build nettest
#
###########################################################################

MK_OS			= host
MK_ELF_TARGET 	= nettest

MK_SRC_FILES = nettest.c

LDLIBS += -lpthread

include ../../rules/mkRules.mk

