###########################################################################
#
#	Makefile to build sertest
#
###########################################################################

MK_OS			= host
MK_ELF_TARGET 	= servo-test

MK_SRC_FILES = servo-test.c

LDLIBS += -lpthread

include ../../rules/mkRules.mk

